######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 4 00:10:59 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . danadam
INCLUDEPATH += .

# Input
HEADERS += \
    MyQtDebug.h \
    QtUnixSignalEmitter.h \

SOURCES += \
    main.cpp \
    QtUnixSignalEmitter.cpp \

